### ISSUE TITLE
Scrolling outside the window affects the map

### ISSUE THREAD

**Issue by Martysh12** [Vrabbers/bnbnav-net-client#15] opened 2023-01-18 23:36 UTC
## Problem
When you scroll outside the window, _it doesn't do anything_, but it secretly affects some internal scroll counter.
After you finish scrolling, if you scroll **inside** the window, it updates the secret internal scroll counter, and the zoom _"jumps"_ to it.

Here's a demo:
![Peek 2023-01-19 01-33](https://user-images.githubusercontent.com/49569238/213318313-cd4c5417-7791-449f-a98c-1521f310b372.gif)

## Solution
This might be an upstream Avalonia UI bug, but I'm not sure. Needs more investigating.

**Comment by Royce551** [comment] 2023-01-20 07:45
Can't reproduce on Windows (main branch). Wouldn't be surprised if it was an Avalonia platform bug (you should raise an issue with them)

**Comment by Vrabbers** [comment] 2023-01-20 22:20
can't repro on windows 11 either

**Comment by Martysh12** [comment] 2023-01-20 22:21
Must be a Linux issue then

**Comment by vicr123** [comment] 2023-01-20 22:23
Can reproduce on Linux

**Comment by Vrabbers** [comment] 2023-01-21 17:38
As this seems to be an Avalonia bug, please report it over at the Avalonia repository, closing this.

**Closed as completed by Vrabbers** 2023-01-21 17:38 UTC
